<?php

declare(strict_types=1);

namespace Symfinity\OmniaIpsum\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('omnia_ipsum');

        /** @psalm-suppress UndefinedMethod */
        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('images')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_provider')
                            ->defaultValue('picsum')
                            ->info('Default image provider: picsum, placeholder, dummyimage, placehold, ui-avatars')
                        ->end()
                        ->integerNode('default_width')
                            ->defaultValue(600)
                            ->min(1)
                            ->max(5000)
                        ->end()
                        ->integerNode('default_height')
                            ->defaultValue(400)
                            ->min(1)
                            ->max(5000)
                        ->end()
                        ->scalarNode('default_background')
                            ->defaultValue('cccccc')
                        ->end()
                        ->scalarNode('default_foreground')
                            ->defaultValue('333333')
                        ->end()
                        ->scalarNode('default_text')
                            ->defaultNull()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('text')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('default_paragraphs')
                            ->defaultValue(3)
                            ->min(1)
                            ->max(100)
                        ->end()
                        ->integerNode('default_sentences')
                            ->defaultValue(5)
                            ->min(1)
                            ->max(100)
                        ->end()
                        ->integerNode('default_words')
                            ->defaultValue(50)
                            ->min(1)
                            ->max(1000)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('videos')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_provider')
                            ->defaultValue('gcs')
                            ->info('Default video provider: gcs (Google Cloud Storage)')
                        ->end()
                        ->integerNode('default_width')
                            ->defaultValue(1920)
                            ->min(1)
                            ->max(3840)
                        ->end()
                        ->integerNode('default_height')
                            ->defaultValue(1080)
                            ->min(1)
                            ->max(2160)
                        ->end()
                        ->integerNode('default_duration')
                            ->defaultValue(30)
                            ->min(1)
                            ->max(120)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('audios')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_provider')
                            ->defaultValue('silence')
                            ->info('Default audio provider: silence')
                        ->end()
                        ->integerNode('default_duration')
                            ->defaultValue(10)
                            ->min(1)
                            ->max(60)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('faker')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('locale')
                            ->defaultValue('en_US')
                            ->info('Faker locale (e.g., de_DE, fr_FR, en_US)')
                        ->end()
                        ->integerNode('seed')
                            ->defaultNull()
                            ->info('Seed for reproducible fake data')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
